### PR TITLE
Remove download without SHA-check

### PR DESCRIPTION
**Pull request by mathiascode**
Such issues should be reported to us, not ignored.

### CODE REVIEW

**Review by madmaxoft — APPROVED** [review]

**Review by bearbin — APPROVED** [review]

**Comment by ItsShadowCone** [comment]
The original intention wasn't that this could have been an error on our side, but it rather followed the mindset of the time. Originally, most security features were optionally opt-in. At some point they became enabled by default but still simple to disable (or fallback) as to not break usability. In recent days, there has been a shift towards opinionated "security-or-fail" software design in the western world, which we might as well just follow here.

In the end it boils down to the security - usability tradeoff and i'm happy to tread along with that decision, but keep in mind that the most important use case of download integrity protection is exactly that: protecting about faulty bits. While there might be a slim chance that someone is attacking the download and the SHA check is actually thwarting that attack, it should be kept in mind that the actual transport security of the downloads should be provided by the TLS stack, not by a custom made hash integrity protection that is served over an equally (in)secure channel.

As such it might be noteworthy that since this integrity check doesn't actually provide any security on its own, we might at some point "upgrade" to a larger hash, but there is absolutely no need to do that.

As a side note, the application should maybe just retry downloading the whole binary+sha package on failure (but only once please) to see if that automatically fixes the error, and otherwise refer to the bugtracker.

**Comment by tigerw** [comment]
In what circumstance would download succeed but return invalid bits?

**Comment by madmaxoft** [comment]
You obviously don't remember the "good old times" where bit rot affected any connection and checksumming was the only way to protect against such failures when downloading. Yes, it does happen.

**Comment by tigerw** [comment]
I likely wasn't alive then :)

I suppose then that the TCP checksum wasn't enough and let some slip through?

**Comment by ItsShadowCone** [comment]
Well it still happens all the time, but you dont really notice usually... partly because ip checksums are not too bad actually, and mostly because there's better checksums for literally everything that's deployed at scale.... Usually it's not a risk for an individual, but once you scale it up, problems _will_ surface every day.... Also as long as it's automated and doesn't add too much time / performance cost, you should just do it.

**Pull request merged**
