### PR TITLE
Update download URL

### PR DESCRIPTION
**Pull request by mathiascode**

### CODE REVIEW

**Comment by tigerw** [comment]
Take the forbidden path - commit directly to master today!

**Comment by mathiascode** [comment]
No such permissions in Android land

**Review by bearbin — APPROVED** [review]

**Comment by bearbin** [comment]
Now to create a release for the new version; and upload it to the store. I'm not sure of the process for that...

**Comment by mathiascode** [comment]
The process so far has been me building a new apk, and @Cl1608Ho signing it and tagging a new release. Cuberite was removed from the Play Store more than a year ago due to breaking the TOS.

**Comment by tigerw** [comment]
Must have been a stupid TOS.

**Pull request merged**
