### PR TITLE
Add copyright owner to license

### PR DESCRIPTION
**Pull request by mathiascode**

### CODE REVIEW

**Comment by madmaxoft** [comment]
Does the year need to be specified? It only leads to forgotten years and yearly updates on the numbers, completely needless.

**Comment by mathiascode** [comment]
As far as I can tell, it should be enough to specify the year the copyright was introduced (2016), but as with all other things, there seem to be mixed opinions online.

**Review by bearbin — APPROVED** [review]
I don't really see the harm in having the year, if nothing else it gives a way to date the software if someone finds a copy of it in the future.

**Review by ItsShadowCone — CHANGES_REQUESTED** [review]
People usually get this wrong, but the copyright year is the year where this was first published or used, and by design doesnt have an end date attached to it (because that's defined by law and cannot be altered by you putting a notice on it). One could obviously argue that creating a new version of it that significantly differs allows you to change the first publication year to this date, which would extend the (I think 70 year) period, but I don't think that's what we are talking about here.

Anyway, these notices are generally nice to have but aren't actually mandatory usually since you *have* copyright no matter what you put in it (unless you express that you turn it into public domain). 

My opinion is make it 2016 or 2018 or 2020 if you want but stick to one reasonable number.

**Comment by mathiascode** [comment]
I'd say 2016 would be reasonable then, if we want to avoid updating the year.

**Review by ItsShadowCone — APPROVED** [review]

**Pull request merged**
